version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: pararel_hw3:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
      
networks:
  webnet:
